LE_EMAIL=
LE_DOMAIN=
#variables wordpress
WORDPRESS_DB_NAME=
WORDPRESS_DB_USER=
WORDPRESS_DB_PASSWORD=
IP_CLIENTE_MYSQL=
WORDPRESS_DB_HOST=
###PAGINA
WORDPRESS_DIRECTORY=
CERTIFICATE_DOMAIN=
WORDPRESS_TITLE=
WORDPRESS_USER=
WORDPRESS_PASSWORD=
WORDPRESS_EMAIL=
WORDPRESS_HIDE_LOGIN_URL=